Vagrant.configure("2") do |config|

  config.vm.define "logger" do |cfg|
    cfg.vm.box = "bento/ubuntu-16.04"
    cfg.vm.hostname = "logger"
    config.vm.provision :shell, path: "bootstrap.sh"
    cfg.vm.network :private_network, ip: "192.168.30.105", gateway: "192.168.30.1", dns: "8.8.8.8"

    # disables annoying prompt about "Preparing SMB shared folders"
    cfg.vm.synced_folder ".", "/vagrant", disabled: true

    cfg.vm.provider "vmware_fusion" do |v, override|
      v.vmx["displayname"] = "logger"
      v.memory = 2048
      v.cpus = 1
      v.gui = true
    end

    cfg.vm.provider "vmware_desktop" do |v, override|
      v.vmx["displayname"] = "logger"
      v.memory = 4096
      v.cpus = 2
      v.gui = true
    end

    cfg.vm.provider "virtualbox" do |vb, override|
      vb.gui = true
      vb.name = "logger"
      vb.customize ["modifyvm", :id, "--memory", 4096]
      vb.customize ["modifyvm", :id, "--cpus", 2]
      vb.customize ["modifyvm", :id, "--vram", "32"]
      vb.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
      vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
      vb.customize ["setextradata", "global", "GUI/SuppressMessages", "all" ]
    end
    
    cfg.vm.provider :vmware_esxi do |esxi|
      esxi.esxi_hostname = '192.168.1.8'
      esxi.esxi_username = 'root'
      esxi.esxi_password = 'file:C:\Users\david\Desktop\keys\vagrant.txt'
      esxi.esxi_hostport = 22
      esxi.esxi_disk_store = 'datastore1'
      esxi.esxi_resource_pool = '/VAGRANT'
      esxi.guest_memsize = '2048'
      esxi.guest_numvcpus  = '2'
      esxi.esxi_virtual_network = ['TESTLAB']
    end


  end

  config.vm.define "dc" do |cfg|
    cfg.vm.box = "../Boxes/windows_2016_vmware.box"
    cfg.vm.hostname = "dc"
    cfg.vm.boot_timeout = 600
    # use the plaintext WinRM transport and force it to use basic authentication.
    # NB this is needed because the default negotiate transport stops working
    #    after the domain controller is installed.
    #    see https://groups.google.com/forum/#!topic/vagrant-up/sZantuCM0q4
    cfg.winrm.transport = :plaintext
    cfg.vm.communicator = "winrm"
    cfg.winrm.basic_auth_only = true
    cfg.winrm.timeout = 300
    cfg.winrm.retry_limit = 20
    cfg.vm.network :private_network, ip: "192.168.30.102", gateway: "192.168.30.1"

    # disables annoying prompt about "Preparing SMB shared folders"
    cfg.vm.synced_folder ".", "/vagrant", disabled: true

    cfg.vm.provision "shell", path: "scripts/fix-second-network.ps1", privileged: false, args: "192.168.30.102"
    cfg.vm.provision "shell", path: "scripts/provision.ps1", privileged: false
    cfg.vm.provision "reload"
    cfg.vm.provision "shell", path: "scripts/provision.ps1", privileged: false
    cfg.vm.provision "shell", path: "scripts/download_palantir_wef.ps1", privileged: true
    cfg.vm.provision "shell", path: "scripts/download_palantir_osquery.ps1", privileged: true
    cfg.vm.provision "shell", path: "scripts/install-splunkuf.ps1", privileged: true
    cfg.vm.provision "shell", path: "scripts/install-inputsconf.ps1", privileged: true
    cfg.vm.provision "shell", path: "scripts/install-utilities.ps1", privileged: true
    cfg.vm.provision "shell", path: "scripts/install-osquery.ps1", privileged: true
    cfg.vm.provision "shell", path: "scripts/install-caldera-agent.ps1", privileged: true
    cfg.vm.provision "shell", path: "scripts/install-sysinternals.ps1", privileged: true
    cfg.vm.provision "shell", path: "scripts/configure-ou.ps1", privileged: true
    cfg.vm.provision "shell", path: "scripts/configure-wef-gpo.ps1", privileged: true
    cfg.vm.provision "shell", path: "scripts/configure-powershelllogging.ps1", privileged: true
    cfg.vm.provision "shell", path: "scripts/configure-AuditingPolicyGPOs.ps1", privileged: true
    cfg.vm.provision "shell", path: "scripts/install-autorunstowineventlog.ps1", privileged: true
    cfg.vm.provision "shell", inline: 'wevtutil el | Foreach-Object {wevtutil cl "$_"}', privileged: true
    cfg.vm.provision "shell", inline: "Set-SmbServerConfiguration -AuditSmb1Access $true -Force", privileged: true

    cfg.vm.provider "vmware_fusion" do |v, override|
      override.vm.box = "../Boxes/windows_2016_vmware.box"
      v.vmx["displayname"] = "dc.windomain.local"
      v.memory = 2560
      v.cpus = 2
      v.gui = true
    end

    cfg.vm.provider "vmware_desktop" do |v, override|
      override.vm.box = "../Boxes/windows_2016_vmware.box"
      v.vmx["displayname"] = "dc.windomain.local"
      v.memory = 2560
      v.cpus = 2
      v.gui = true
      v.enable_vmrun_ip_lookup = false
    end

    cfg.vm.provider "virtualbox" do |vb, override|
      vb.gui = true
      vb.name = "dc.windomain.local"
      vb.customize ["modifyvm", :id, "--memory", 2560]
      vb.customize ["modifyvm", :id, "--cpus", 2]
      vb.customize ["modifyvm", :id, "--vram", "32"]
      vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
      vb.customize ["setextradata", "global", "GUI/SuppressMessages", "all" ]
    end

    cfg.vm.provider :vmware_esxi do |esxi|
      esxi.esxi_hostname = '192.168.1.8'
      esxi.esxi_username = 'root'
      esxi.esxi_password = 'file:C:\Users\david\Desktop\keys\vagrant.txt'
      esxi.esxi_hostport = 22
      esxi.esxi_disk_store = 'datastore1'
      esxi.esxi_resource_pool = '/VAGRANT'
      esxi.guest_memsize = '2048'
      esxi.guest_numvcpus  = '2'
      esxi.esxi_virtual_network = ['TESTLAB']
    end
  end

  config.vm.define "wef" do |cfg|
    cfg.vm.box = "../Boxes/windows_2016_vmware.box"
    cfg.vm.hostname = "wef"
    cfg.vm.boot_timeout = 600
    cfg.vm.communicator = "winrm"
    cfg.winrm.basic_auth_only = true
    cfg.winrm.timeout = 300
    cfg.winrm.retry_limit = 20
    cfg.vm.network :private_network, ip: "192.168.30.103", gateway: "192.168.30.1", dns: "192.168.30.102"

    # disables annoying prompt about "Preparing SMB shared folders"
    cfg.vm.synced_folder ".", "/vagrant", disabled: true

    cfg.vm.provision "shell", path: "scripts/fix-second-network.ps1", privileged: false, args: "-ip 192.168.30.103 -dns 192.168.30.102"
    cfg.vm.provision "shell", path: "scripts/provision.ps1", privileged: false
    cfg.vm.provision "reload"
    cfg.vm.provision "shell", path: "scripts/provision.ps1", privileged: false
    cfg.vm.provision "shell", path: "scripts/download_palantir_wef.ps1", privileged: true
    cfg.vm.provision "shell", path: "scripts/download_palantir_osquery.ps1", privileged: true
    cfg.vm.provision "shell", inline: 'wevtutil el | Foreach-Object {wevtutil cl "$_"}', privileged: true
    cfg.vm.provision "shell", path: "scripts/install-wefsubscriptions.ps1", privileged: true
    cfg.vm.provision "shell", path: "scripts/install-splunkuf.ps1", privileged: true
    cfg.vm.provision "shell", path: "scripts/install-windows_ta.ps1", privileged: true
    cfg.vm.provision "shell", path: "scripts/install-inputsconf.ps1", privileged: true
    cfg.vm.provision "shell", path: "scripts/install-utilities.ps1", privileged: true
    cfg.vm.provision "shell", path: "scripts/install-osquery.ps1", privileged: true
    cfg.vm.provision "shell", path: "scripts/install-caldera-agent.ps1", privileged: true
    cfg.vm.provision "shell", path: "scripts/install-sysinternals.ps1", privileged: true
    cfg.vm.provision "shell", path: "scripts/configure-pslogstranscriptsshare.ps1", privileged: true
    cfg.vm.provision "shell", path: "scripts/install-autorunstowineventlog.ps1", privileged: true
    cfg.vm.provision "shell", inline: "Set-SmbServerConfiguration -AuditSmb1Access $true -Force", privileged: true
    cfg.vm.provision "shell", path: "scripts/install-microsoft-ata.ps1", privileged: true

    cfg.vm.provider "vmware_fusion" do |v, override|
      override.vm.box = "../Boxes/windows_2016_vmware.box"
      v.vmx["displayname"] = "wef.windomain.local"
      v.memory = 2048
      v.cpus = 2
      v.gui = true
    end

    cfg.vm.provider "vmware_desktop" do |v, override|
      override.vm.box = "../Boxes/windows_2016_vmware.box"
      v.vmx["displayname"] = "wef.windomain.local"
      v.memory = 2048
      v.cpus = 2
      v.gui = true
      v.enable_vmrun_ip_lookup = false
    end

    cfg.vm.provider "virtualbox" do |vb, override|
      vb.gui = true
      vb.name = "wef.windomain.local"
      vb.customize ["modifyvm", :id, "--memory", 2048]
      vb.customize ["modifyvm", :id, "--cpus", 2]
      vb.customize ["modifyvm", :id, "--vram", "32"]
      vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
      vb.customize ["setextradata", "global", "GUI/SuppressMessages", "all" ]      
    end

    cfg.vm.provider :vmware_esxi do |esxi|
      esxi.esxi_hostname = '192.168.1.8'
      esxi.esxi_username = 'root'
      esxi.esxi_password = 'file:C:\Users\david\Desktop\keys\vagrant.txt'
      esxi.esxi_hostport = 22
      esxi.esxi_disk_store = 'datastore1'
      esxi.esxi_resource_pool = '/VAGRANT'
      esxi.guest_memsize = '2048'
      esxi.guest_numvcpus  = '2'
      esxi.esxi_virtual_network = ['TESTLAB']
    end
  end

  config.vm.define "win10" do |cfg|
    cfg.vm.box = "../Boxes/windows_10_vmware.box"
    cfg.vm.hostname = "win10"
    cfg.vm.boot_timeout = 600
    cfg.vm.communicator = "winrm"
    cfg.winrm.basic_auth_only = true
    cfg.winrm.timeout = 300
    cfg.winrm.retry_limit = 20
    cfg.vm.network :private_network, ip: "192.168.30.104", gateway: "192.168.30.1", dns: "192.168.30.102"

    # disables annoying prompt about "Preparing SMB shared folders"
    cfg.vm.synced_folder ".", "/vagrant", disabled: true

    cfg.vm.provision "shell", path: "scripts/fix-second-network.ps1", privileged: false, args: "-ip 192.168.30.104 -dns 192.168.30.102"
    cfg.vm.provision "shell", path: "scripts/provision.ps1", privileged: false
    cfg.vm.provision "reload"
    cfg.vm.provision "shell", path: "scripts/provision.ps1", privileged: false
    cfg.vm.provision "shell", path: "scripts/download_palantir_wef.ps1", privileged: true
    cfg.vm.provision "shell", path: "scripts/download_palantir_osquery.ps1", privileged: true
    cfg.vm.provision "shell", path: "scripts/MakeWindows10GreatAgain.ps1", privileged: true
    cfg.vm.provision "shell", inline: 'wevtutil el | Foreach-Object {wevtutil cl "$_"}', privileged: true
    cfg.vm.provision "shell", path: "scripts/install-splunkuf.ps1", privileged: true
    cfg.vm.provision "shell", path: "scripts/install-utilities.ps1", privileged: true
    cfg.vm.provision "shell", path: "scripts/install-osquery.ps1", privileged: true
    cfg.vm.provision "shell", path: "scripts/install-caldera-agent.ps1", privileged: true
    cfg.vm.provision "shell", path: "scripts/install-inputsconf.ps1", privileged: true
    cfg.vm.provision "shell", path: "scripts/install-sysinternals.ps1", privileged: true
    cfg.vm.provision "shell", path: "scripts/install-autorunstowineventlog.ps1", privileged: true

    cfg.vm.provider "vmware_fusion" do |v, override|
      override.vm.box = "../Boxes/windows_10_vmware.box"
      v.vmx["displayname"] = "win10.windomain.local"
      v.vmx["gui.fullscreenatpoweron"] = "FALSE"
      v.vmx["gui.viewModeAtPowerOn"] = "windowed"
      v.vmx["gui.fitguestusingnativedisplayresolution"] = "FALSE"
      v.memory = 2048
      v.cpus = 1
      v.gui = true
    end

    cfg.vm.provider "vmware_desktop" do |v, override|
      override.vm.box = "../Boxes/windows_10_vmware.box"
      v.vmx["displayname"] = "win10.windomain.local"
      v.vmx["gui.fullscreenatpoweron"] = "FALSE"
      v.vmx["gui.viewModeAtPowerOn"] = "windowed"
      v.memory = 2048
      v.cpus = 1
      v.gui = true
      v.enable_vmrun_ip_lookup = false
    end

    cfg.vm.provider "virtualbox" do |vb, override|
      vb.gui = true
      vb.name = "win10.windomain.local"
      vb.customize ["modifyvm", :id, "--memory", 2048]
      vb.customize ["modifyvm", :id, "--cpus", 1]
      vb.customize ["modifyvm", :id, "--vram", "32"]
      vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
      vb.customize ["setextradata", "global", "GUI/SuppressMessages", "all" ]
    end

    cfg.vm.provider :vmware_esxi do |esxi|
      esxi.esxi_hostname = '192.168.1.8'
      esxi.esxi_username = 'root'
      esxi.esxi_password = 'file:C:\Users\david\Desktop\keys\vagrant.txt'
      esxi.esxi_hostport = 22
      esxi.esxi_disk_store = 'datastore1'
      esxi.esxi_resource_pool = '/VAGRANT'
      esxi.guest_memsize = '2048'
      esxi.guest_numvcpus  = '2'
      esxi.esxi_virtual_network = ['TESTLAB']
    end
  end
end
